[build]
  base = "frontend"
  publish = "build"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "18.18.2"
  YARN_VERSION = "1.22.22"

[[plugins]]
package = "@netlify/plugin-visual-editor"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

 [[redirects]]
  from = "/admin/login"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/signup"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/reset-password"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://hhsbands-api.netlify.app"

[context.deploy-preview.environment]
  REACT_APP_BACKEND_URL = "https://hhsbands-api.netlify.app"

[context.branch-deploy.environment]
  REACT_APP_BACKEND_URL = "https://hhsbands-api.netlify.app"
